//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVLMS.CoursePlayer.CourseStatusSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusData", Namespace="http://schemas.datacontract.org/2004/07/ServiceLearnerStatus")]
    [System.SerializableAttribute()]
    public partial class StatusData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dsStatusDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dsStatusData {
            get {
                return this.dsStatusDataField;
            }
            set {
                if ((object.ReferenceEquals(this.dsStatusDataField, value) != true)) {
                    this.dsStatusDataField = value;
                    this.RaisePropertyChanged("dsStatusData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseStatusSvc.IGetLearnerStatus")]
    public interface IGetLearnerStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetLearnerStatus/GetLearnerData", ReplyAction="http://tempuri.org/IGetLearnerStatus/GetLearnerDataResponse")]
        BVLMS.CoursePlayer.CourseStatusSvc.StatusData GetLearnerData(string pstrRootUserDataXmlPath, string pstrClientId, string pstrCourseId, string pstrLearnerId, string pstrAttempId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetLearnerStatus/Test", ReplyAction="http://tempuri.org/IGetLearnerStatus/TestResponse")]
        string Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetLearnerStatusChannel : BVLMS.CoursePlayer.CourseStatusSvc.IGetLearnerStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLearnerStatusClient : System.ServiceModel.ClientBase<BVLMS.CoursePlayer.CourseStatusSvc.IGetLearnerStatus>, BVLMS.CoursePlayer.CourseStatusSvc.IGetLearnerStatus {
        
        public GetLearnerStatusClient() {
        }
        
        public GetLearnerStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetLearnerStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetLearnerStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetLearnerStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BVLMS.CoursePlayer.CourseStatusSvc.StatusData GetLearnerData(string pstrRootUserDataXmlPath, string pstrClientId, string pstrCourseId, string pstrLearnerId, string pstrAttempId) {
            return base.Channel.GetLearnerData(pstrRootUserDataXmlPath, pstrClientId, pstrCourseId, pstrLearnerId, pstrAttempId);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
    }
}
